services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-alex-cour-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    networks:
      - alex-cour-net
    volumes:
      - postgres-volume:/data/postgres
      - ../scripts/db-initializer.sh:/usr/local/bin/db-initializer.sh
      - ../scripts/custom-db-entrypoint.sh:/custom-db-entrypoint.sh
    entrypoint: /custom-db-entrypoint.sh
    restart: unless-stopped


networks:
  alex-cour-net:
    external: true

volumes:
  postgres-volume: